/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    windows: Window;
    articles: Article;
    'cookie-services': CookieService;
    'cookie-consents': CookieConsent;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    windows: WindowsSelect<false> | WindowsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'cookie-services': CookieServicesSelect<false> | CookieServicesSelect<true>;
    'cookie-consents': CookieConsentsSelect<false> | CookieConsentsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'cookie-settings': CookieSetting;
  };
  globalsSelect: {
    'cookie-settings': CookieSettingsSelect<false> | CookieSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "windows".
 */
export interface Window {
  id: number;
  title: string;
  /**
   * URL path identifier, e.g. "about" → /about
   */
  slug: string;
  content?:
    | (
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            images?:
              | {
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embed';
          }
        | {
            heading: string;
            body?: string | null;
            link?: {
              label?: string | null;
              href?: string | null;
              openInNewTab?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            /**
             * Which article types to include in this list
             */
            types: ('case-study' | 'service')[];
            sortField?: ('createdAt' | 'updatedAt' | 'title' | 'shortcutOrder') | null;
            sortDirection?: ('desc' | 'asc') | null;
            /**
             * Maximum number of articles to display
             */
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'articleList';
          }
      )[]
    | null;
  showShortcut?: boolean | null;
  shortcutName?: string | null;
  shortcutIcon?: string | null;
  /**
   * Controls position across all shortcuts. Lower = earlier. Leave blank to append.
   */
  shortcutOrder?: number | null;
  /**
   * Show minimize button in the title bar (default: on). Uncheck to hide it.
   */
  windowCollapsible?: boolean | null;
  /**
   * Show full-screen expand button in the title bar (default: off).
   */
  windowExpandable?: boolean | null;
  /**
   * Allow the window to be resized by dragging its edges (default: on).
   */
  windowResizable?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  type: 'case-study' | 'service';
  /**
   * URL path identifier, e.g. "my-project" → /my-project
   */
  slug: string;
  content?:
    | (
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            images?:
              | {
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embed';
          }
        | {
            heading: string;
            body?: string | null;
            link?: {
              label?: string | null;
              href?: string | null;
              openInNewTab?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            /**
             * Which article types to include in this list
             */
            types: ('case-study' | 'service')[];
            sortField?: ('createdAt' | 'updatedAt' | 'title' | 'shortcutOrder') | null;
            sortDirection?: ('desc' | 'asc') | null;
            /**
             * Maximum number of articles to display
             */
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'articleList';
          }
      )[]
    | null;
  showShortcut?: boolean | null;
  shortcutName?: string | null;
  shortcutIcon?: string | null;
  /**
   * Controls position across all shortcuts. Lower = earlier. Leave blank to append.
   */
  shortcutOrder?: number | null;
  /**
   * Show minimize button in the title bar (default: on). Uncheck to hide it.
   */
  windowCollapsible?: boolean | null;
  /**
   * Show full-screen expand button in the title bar (default: off).
   */
  windowExpandable?: boolean | null;
  /**
   * Allow the window to be resized by dragging its edges (default: on).
   */
  windowResizable?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-services".
 */
export interface CookieService {
  id: number;
  name: string;
  category: 'essential' | 'functional' | 'analytics' | 'marketing';
  description?: string | null;
  /**
   * Legal entity name, e.g. "Google LLC"
   */
  legalName?: string | null;
  /**
   * Link to the service privacy policy
   */
  privacyPolicyUrl?: string | null;
  cookies?:
    | {
        storageType?: ('cookie' | 'localStorage' | 'sessionStorage' | 'indexedDB' | 'other') | null;
        /**
         * e.g. _grecaptcha, _ph_opt_in_out_*, _ga
         */
        name?: string | null;
        /**
         * e.g. "1 year", "Session", "Persistent"
         */
        duration?: string | null;
        /**
         * What this specific cookie/item is used for
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Audit log of all cookie consent events. Do not edit manually.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-consents".
 */
export interface CookieConsent {
  id: number;
  /**
   * UUID generated client-side. Each consent event (including updates) gets a fresh ID.
   */
  consentId: string;
  categories: ('essential' | 'functional' | 'analytics' | 'marketing')[];
  /**
   * Auto-captured from request headers
   */
  ipAddress?: string | null;
  /**
   * Auto-captured from request headers
   */
  userAgent?: string | null;
  /**
   * Browser language (navigator.language)
   */
  language?: string | null;
  /**
   * CookieSettings.consentVersion at time of consent
   */
  consentVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  /**
   * Used as the URL path: /contact → /contact
   */
  slug: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            required?: boolean | null;
            defaultValue?: string | null;
            /**
             * Lock this field — default value is enforced on submit
             */
            isPreDefined?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            required?: boolean | null;
            defaultValue?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            required?: boolean | null;
            defaultValue?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  showShortcut?: boolean | null;
  shortcutName?: string | null;
  shortcutIcon?: string | null;
  /**
   * Controls position across all shortcuts. Lower = earlier. Leave blank to append.
   */
  shortcutOrder?: number | null;
  /**
   * Show minimize button in the title bar (default: on). Uncheck to hide it.
   */
  windowCollapsible?: boolean | null;
  /**
   * Show full-screen expand button in the title bar (default: off).
   */
  windowExpandable?: boolean | null;
  /**
   * Allow the window to be resized by dragging its edges (default: on).
   */
  windowResizable?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'windows';
        value: number | Window;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'cookie-services';
        value: number | CookieService;
      } | null)
    | ({
        relationTo: 'cookie-consents';
        value: number | CookieConsent;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "windows_select".
 */
export interface WindowsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              url?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                    openInNewTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        articleList?:
          | T
          | {
              heading?: T;
              types?: T;
              sortField?: T;
              sortDirection?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
      };
  showShortcut?: T;
  shortcutName?: T;
  shortcutIcon?: T;
  shortcutOrder?: T;
  windowCollapsible?: T;
  windowExpandable?: T;
  windowResizable?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  slug?: T;
  content?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              url?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                    openInNewTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        articleList?:
          | T
          | {
              heading?: T;
              types?: T;
              sortField?: T;
              sortDirection?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
      };
  showShortcut?: T;
  shortcutName?: T;
  shortcutIcon?: T;
  shortcutOrder?: T;
  windowCollapsible?: T;
  windowExpandable?: T;
  windowResizable?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-services_select".
 */
export interface CookieServicesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  description?: T;
  legalName?: T;
  privacyPolicyUrl?: T;
  cookies?:
    | T
    | {
        storageType?: T;
        name?: T;
        duration?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-consents_select".
 */
export interface CookieConsentsSelect<T extends boolean = true> {
  consentId?: T;
  categories?: T;
  ipAddress?: T;
  userAgent?: T;
  language?: T;
  consentVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  fields?:
    | T
    | {
        email?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              required?: T;
              defaultValue?: T;
              isPreDefined?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  showShortcut?: T;
  shortcutName?: T;
  shortcutIcon?: T;
  shortcutOrder?: T;
  windowCollapsible?: T;
  windowExpandable?: T;
  windowResizable?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configure the cookie consent banner shown to visitors.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-settings".
 */
export interface CookieSetting {
  id: number;
  title?: string | null;
  description?: string | null;
  /**
   * Bump this value (e.g. "1.1", "2.0") to invalidate existing consents and re-ask all visitors.
   */
  consentVersion?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-settings_select".
 */
export interface CookieSettingsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  consentVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}