/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Action buttons pinned to the bottom of the window.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WindowButton".
 */
export type WindowButton =
  | {
      label: string;
      style?: ('primary' | 'secondary') | null;
      target?: ('internal' | 'external') | null;
      /**
       * Slug of the window/page to open, e.g. "works".
       */
      slug?: string | null;
      href?: string | null;
      openInNewTab?: boolean | null;
      id?: string | null;
    }[]
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    windows: Window;
    articles: Article;
    tags: Tag;
    'cookie-services': CookieService;
    'cookie-consents': CookieConsent;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    windows: WindowsSelect<false> | WindowsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'cookie-services': CookieServicesSelect<false> | CookieServicesSelect<true>;
    'cookie-consents': CookieConsentsSelect<false> | CookieConsentsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'cookie-settings': CookieSetting;
  };
  globalsSelect: {
    'cookie-settings': CookieSettingsSelect<false> | CookieSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  seoGeneratedMetaImage?: {
    sourceCollection?: ('windows' | 'articles') | null;
    sourceDocumentId?: string | null;
    contentSignature?: string | null;
    generatedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "windows".
 */
export interface Window {
  id: number;
  title: string;
  /**
   * URL path identifier, e.g. "about" → /about
   */
  slug: string;
  content?:
    | (
        | RichTextBlock
        | ArticleListBlock
        | WelcomeIntroBlock
        | InteractivePortraitBlock
        | SummaryBlock
        | StatsBlock
        | ImageSectionBlock
        | DescriptionBlock
        | TitleBlock
      )[]
    | null;
  buttons?: WindowButton;
  showShortcut?: boolean | null;
  shortcutName?: string | null;
  shortcutIcon?: string | null;
  /**
   * Controls position across all shortcuts. Lower = earlier. Leave blank to append.
   */
  shortcutOrder?: number | null;
  /**
   * Show minimize button in the title bar (default: on). Uncheck to hide it.
   */
  windowCollapsible?: boolean | null;
  /**
   * Show full-screen expand button in the title bar (default: off).
   */
  windowExpandable?: boolean | null;
  /**
   * Allow the window to be resized by dragging its edges (default: on).
   */
  windowResizable?: boolean | null;
  /**
   * Show a search bar in the window toolbar. Sections that support search (e.g. article lists) will filter their content.
   */
  windowDisplaySearch?: boolean | null;
  /**
   * Show grid / table view toggle buttons in the toolbar.
   */
  windowDisplayViewToggle?: boolean | null;
  /**
   * Initial layout when the window is opened.
   */
  windowDefaultView?: ('grid' | 'table') | null;
  /**
   * Allow back / forward navigation within the window. Links that would open a new window will instead navigate in-place and build a per-window history.
   */
  windowDisplayHistory?: boolean | null;
  /**
   * Open this content window automatically on the root desktop/mobile session.
   */
  windowOpenOnStartup?: boolean | null;
  /**
   * Viewport classes where this startup window should open.
   */
  windowStartupViewports?: ('desktop' | 'mobile')[] | null;
  /**
   * Lower numbers open first. Ties fall back to shortcut order and title.
   */
  windowStartupOrder?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleListBlock".
 */
export interface ArticleListBlock {
  heading?: string | null;
  /**
   * Which article types to include in this list
   */
  types: ('case-study' | 'service')[];
  sortField?: ('createdAt' | 'updatedAt' | 'title' | 'shortcutOrder') | null;
  sortDirection?: ('desc' | 'asc') | null;
  /**
   * Maximum number of articles to display
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'articleList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WelcomeIntroBlock".
 */
export interface WelcomeIntroBlock {
  title: string;
  role?: string | null;
  descriptor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'welcomeIntro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InteractivePortraitBlock".
 */
export interface InteractivePortraitBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'interactivePortrait';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SummaryBlock".
 */
export interface SummaryBlock {
  leftTitle?: string | null;
  leftBody?: string | null;
  rightTitle?: string | null;
  rightBody?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'summary';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  /**
   * Up to three large figures shown side by side
   */
  stats?:
    | {
        /**
         * The figure as a single string, e.g. "30Mil", "$30,000", "21%". The number animates; surrounding text stays static.
         */
        value: string;
        /**
         * Caption below the figure
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageSectionBlock".
 */
export interface ImageSectionBlock {
  image: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DescriptionBlock".
 */
export interface DescriptionBlock {
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'description';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleBlock".
 */
export interface TitleBlock {
  title: string;
  role?: string | null;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionTitle';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  type: 'case-study' | 'service';
  /**
   * URL path identifier, e.g. "my-project" → /my-project
   */
  slug: string;
  /**
   * Year the project shipped (shown in the Works table view)
   */
  year?: number | null;
  /**
   * Pick existing tags or create new ones — shown in the Works table view
   */
  tags?: (number | Tag)[] | null;
  /**
   * Background layer (16:9) for the Hero parallax and Works card image
   */
  bgImage?: (number | null) | Media;
  /**
   * Foreground layer (16:9) drawn over the background for the parallax effect
   */
  fgImage?: (number | null) | Media;
  content?:
    | (
        | HeroBlock
        | RichTextBlock
        | ArticleListBlock
        | WelcomeIntroBlock
        | InteractivePortraitBlock
        | SummaryBlock
        | StatsBlock
        | ImageSectionBlock
        | DescriptionBlock
        | TitleBlock
      )[]
    | null;
  buttons?: WindowButton;
  showShortcut?: boolean | null;
  shortcutName?: string | null;
  shortcutIcon?: string | null;
  /**
   * Controls position across all shortcuts. Lower = earlier. Leave blank to append.
   */
  shortcutOrder?: number | null;
  /**
   * Show minimize button in the title bar (default: on). Uncheck to hide it.
   */
  windowCollapsible?: boolean | null;
  /**
   * Show full-screen expand button in the title bar (default: off).
   */
  windowExpandable?: boolean | null;
  /**
   * Allow the window to be resized by dragging its edges (default: on).
   */
  windowResizable?: boolean | null;
  /**
   * Show a search bar in the window toolbar. Sections that support search (e.g. article lists) will filter their content.
   */
  windowDisplaySearch?: boolean | null;
  /**
   * Show grid / table view toggle buttons in the toolbar.
   */
  windowDisplayViewToggle?: boolean | null;
  /**
   * Initial layout when the window is opened.
   */
  windowDefaultView?: ('grid' | 'table') | null;
  /**
   * Allow back / forward navigation within the window. Links that would open a new window will instead navigate in-place and build a per-window history.
   */
  windowDisplayHistory?: boolean | null;
  /**
   * Open this content window automatically on the root desktop/mobile session.
   */
  windowOpenOnStartup?: boolean | null;
  /**
   * Viewport classes where this startup window should open.
   */
  windowStartupViewports?: ('desktop' | 'mobile')[] | null;
  /**
   * Lower numbers open first. Ties fall back to shortcut order and title.
   */
  windowStartupOrder?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  /**
   * URL-safe identifier for the tag, e.g. "branding"
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  title: string;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-services".
 */
export interface CookieService {
  id: number;
  name: string;
  category: 'essential' | 'functional' | 'analytics' | 'marketing';
  description?: string | null;
  /**
   * Legal entity name, e.g. "Google LLC"
   */
  legalName?: string | null;
  /**
   * Link to the service privacy policy
   */
  privacyPolicyUrl?: string | null;
  cookies?:
    | {
        storageType?: ('cookie' | 'localStorage' | 'sessionStorage' | 'indexedDB' | 'other') | null;
        /**
         * e.g. _grecaptcha, _ph_opt_in_out_*, _ga
         */
        name?: string | null;
        /**
         * e.g. "1 year", "Session", "Persistent"
         */
        duration?: string | null;
        /**
         * What this specific cookie/item is used for
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Audit log of all cookie consent events. Do not edit manually.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-consents".
 */
export interface CookieConsent {
  id: number;
  /**
   * UUID generated client-side. Each consent event (including updates) gets a fresh ID.
   */
  consentId: string;
  categories: ('essential' | 'functional' | 'analytics' | 'marketing')[];
  /**
   * Auto-captured from request headers
   */
  ipAddress?: string | null;
  /**
   * Auto-captured from request headers
   */
  userAgent?: string | null;
  /**
   * Browser language (navigator.language)
   */
  language?: string | null;
  /**
   * CookieSettings.consentVersion at time of consent
   */
  consentVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  /**
   * Used as the URL path: /contact → /contact
   */
  slug: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            required?: boolean | null;
            defaultValue?: string | null;
            /**
             * Lock this field — default value is enforced on submit
             */
            isPreDefined?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            required?: boolean | null;
            defaultValue?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            required?: boolean | null;
            defaultValue?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  showShortcut?: boolean | null;
  shortcutName?: string | null;
  shortcutIcon?: string | null;
  /**
   * Controls position across all shortcuts. Lower = earlier. Leave blank to append.
   */
  shortcutOrder?: number | null;
  /**
   * Show minimize button in the title bar (default: on). Uncheck to hide it.
   */
  windowCollapsible?: boolean | null;
  /**
   * Show full-screen expand button in the title bar (default: off).
   */
  windowExpandable?: boolean | null;
  /**
   * Allow the window to be resized by dragging its edges (default: on).
   */
  windowResizable?: boolean | null;
  /**
   * Show a search bar in the window toolbar. Sections that support search (e.g. article lists) will filter their content.
   */
  windowDisplaySearch?: boolean | null;
  /**
   * Show grid / table view toggle buttons in the toolbar.
   */
  windowDisplayViewToggle?: boolean | null;
  /**
   * Initial layout when the window is opened.
   */
  windowDefaultView?: ('grid' | 'table') | null;
  /**
   * Allow back / forward navigation within the window. Links that would open a new window will instead navigate in-place and build a per-window history.
   */
  windowDisplayHistory?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'windows';
        value: number | Window;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'cookie-services';
        value: number | CookieService;
      } | null)
    | ({
        relationTo: 'cookie-consents';
        value: number | CookieConsent;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  seoGeneratedMetaImage?:
    | T
    | {
        sourceCollection?: T;
        sourceDocumentId?: T;
        contentSignature?: T;
        generatedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "windows_select".
 */
export interface WindowsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        articleList?: T | ArticleListBlockSelect<T>;
        welcomeIntro?: T | WelcomeIntroBlockSelect<T>;
        interactivePortrait?: T | InteractivePortraitBlockSelect<T>;
        summary?: T | SummaryBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        imageSection?: T | ImageSectionBlockSelect<T>;
        description?: T | DescriptionBlockSelect<T>;
        sectionTitle?: T | TitleBlockSelect<T>;
      };
  buttons?: T | WindowButtonSelect<T>;
  showShortcut?: T;
  shortcutName?: T;
  shortcutIcon?: T;
  shortcutOrder?: T;
  windowCollapsible?: T;
  windowExpandable?: T;
  windowResizable?: T;
  windowDisplaySearch?: T;
  windowDisplayViewToggle?: T;
  windowDefaultView?: T;
  windowDisplayHistory?: T;
  windowOpenOnStartup?: T;
  windowStartupViewports?: T;
  windowStartupOrder?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleListBlock_select".
 */
export interface ArticleListBlockSelect<T extends boolean = true> {
  heading?: T;
  types?: T;
  sortField?: T;
  sortDirection?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WelcomeIntroBlock_select".
 */
export interface WelcomeIntroBlockSelect<T extends boolean = true> {
  title?: T;
  role?: T;
  descriptor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InteractivePortraitBlock_select".
 */
export interface InteractivePortraitBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SummaryBlock_select".
 */
export interface SummaryBlockSelect<T extends boolean = true> {
  leftTitle?: T;
  leftBody?: T;
  rightTitle?: T;
  rightBody?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageSectionBlock_select".
 */
export interface ImageSectionBlockSelect<T extends boolean = true> {
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DescriptionBlock_select".
 */
export interface DescriptionBlockSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleBlock_select".
 */
export interface TitleBlockSelect<T extends boolean = true> {
  title?: T;
  role?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WindowButton_select".
 */
export interface WindowButtonSelect<T extends boolean = true> {
  label?: T;
  style?: T;
  target?: T;
  slug?: T;
  href?: T;
  openInNewTab?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  slug?: T;
  year?: T;
  tags?: T;
  bgImage?: T;
  fgImage?: T;
  content?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        articleList?: T | ArticleListBlockSelect<T>;
        welcomeIntro?: T | WelcomeIntroBlockSelect<T>;
        interactivePortrait?: T | InteractivePortraitBlockSelect<T>;
        summary?: T | SummaryBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        imageSection?: T | ImageSectionBlockSelect<T>;
        description?: T | DescriptionBlockSelect<T>;
        sectionTitle?: T | TitleBlockSelect<T>;
      };
  buttons?: T | WindowButtonSelect<T>;
  showShortcut?: T;
  shortcutName?: T;
  shortcutIcon?: T;
  shortcutOrder?: T;
  windowCollapsible?: T;
  windowExpandable?: T;
  windowResizable?: T;
  windowDisplaySearch?: T;
  windowDisplayViewToggle?: T;
  windowDefaultView?: T;
  windowDisplayHistory?: T;
  windowOpenOnStartup?: T;
  windowStartupViewports?: T;
  windowStartupOrder?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-services_select".
 */
export interface CookieServicesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  description?: T;
  legalName?: T;
  privacyPolicyUrl?: T;
  cookies?:
    | T
    | {
        storageType?: T;
        name?: T;
        duration?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-consents_select".
 */
export interface CookieConsentsSelect<T extends boolean = true> {
  consentId?: T;
  categories?: T;
  ipAddress?: T;
  userAgent?: T;
  language?: T;
  consentVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  fields?:
    | T
    | {
        email?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              required?: T;
              defaultValue?: T;
              isPreDefined?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  showShortcut?: T;
  shortcutName?: T;
  shortcutIcon?: T;
  shortcutOrder?: T;
  windowCollapsible?: T;
  windowExpandable?: T;
  windowResizable?: T;
  windowDisplaySearch?: T;
  windowDisplayViewToggle?: T;
  windowDefaultView?: T;
  windowDisplayHistory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configure the cookie consent banner shown to visitors.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-settings".
 */
export interface CookieSetting {
  id: number;
  title?: string | null;
  description?: string | null;
  /**
   * Bump this value (e.g. "1.1", "2.0") to invalidate existing consents and re-ask all visitors.
   */
  consentVersion?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-settings_select".
 */
export interface CookieSettingsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  consentVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}